version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0.0-sdk
        environment:
          - DOTNET_CLI_TELEMETRY_OUTPUT=1
      - image: redis:alpine
      - image: couchbase:community-4.5.1
      
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Build integration tests nuget
          command: |
            mkdir -p /nugets
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.ContextIntegrationTests/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build redis driver nuget
          command: |
            mkdir -p /nugets
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Context.Redis/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build couchbase driver nuget
          command: |
            mkdir -p /nugets
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Context.Couchbase/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build Api Addons nuget
          command: |
            mkdir -p /nugets
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd core/Tweek.ApiService.Addons/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Test redis driver
          command: |
            mkdir -p /nugets
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Context.Redis.IntegrationTests/ && \
            dotnet restore && \
            REDIS_TEST_CONNECTION="127.0.0.1:6379" dotnet test

      - run:
          name: Test couchbase driver
          command: |
            mkdir -p /nugets
            curl --retry 3 --retry-max-time 10 -v http://127.0.0.1:8091/settings/web -d port=8091 -d username=Administrator -d password=password
            curl --retry 3 --retry-max-time 10 -v -u Administrator:password -X POST http://127.0.0.1:8091/pools/default/buckets -d authType=sasl -d name=testbucket -d ramQuotaMB=100 -d saslPassword=password
            export Version=0.1.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Context.Couchbase.IntegrationTests/ && \
            dotnet restore && \
            COUCHBASE_TEST_URL="http://127.0.0.1:8091" dotnet test

      - deploy:
          name: Push nugets
          command: |
            export Version=0.0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ $(git diff-tree --no-commit-id --name-only -r HEAD | grep -cP "addons\/Context|core\/Tweek.ApiService.Addons") != "0" ]]; then
                find /nugets -name "*.nupkg" | xargs -n1 dotnet nuget push -s nuget.org -k $NUGET_APIKEY -n -d
              else
                echo "Code didn't change will not push the nuget"
              fi
            else
              echo "Will not push nuget from non-master branch"
            fi

workflows:
  version: 2
  build_test_and_push:
    jobs:
      - build
