version: '3.1'

services:
  management:
    environment: 
      - GIT_URL=ssh://git@git/tweek/tests
      - GIT_SAMPLE_INTERVAL=500

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  authoring:
    environment: 
      - GIT_URL=ssh://git@git/tweek/tests
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    environment:
      - Rules__Minio__SampleIntervalInMs=500
      # - Rules__Management__SampleIntervalInMs=500
      - CorsPolicies__Keys__Origins=http://editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
  
  selenium:
    image: selenium/standalone-chrome:3.4.0
    container_name: selenium

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
    depends_on: 
      - selenium
      - api
      - authoring
      - management
      - editor
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000/
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on: 
      - api
      - authoring
      - management
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTestDockerfile
    container_name: smoke-tests
    depends_on: 
      - api
      - management
    environment: 
      - TWEEK_API_URL=http://api/

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
